### ISSUE TITLE
Generator fails

### ISSUE THREAD

**Issue by Serginho** [katallaxie/generator-angular2-ts#2]
```
? What is your transpiler typescript

events.js:141
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /opt/nodejs/lib/node_modules/generator-angular2-ts/templates/app/Gruntfile.js
    at EditionInterface.exports._copySingle (/opt/nodejs/lib/node_modules/generator-angular2-ts/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/opt/nodejs/lib/node_modules/generator-angular2-ts/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/opt/nodejs/lib/node_modules/generator-angular2-ts/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:12:8)
    at Generator.template (/opt/nodejs/lib/node_modules/generator-angular2-ts/node_modules/yeoman-generator/lib/actions/actions.js:134:11)
    at Generator.writing (/opt/nodejs/lib/node_modules/generator-angular2-ts/app/generator.js:153:12)
    at /opt/nodejs/lib/node_modules/generator-angular2-ts/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by katallaxie** [comment]
Upps, the templates where not published with the package. 6cb216aacf52cf4a34dd7d6feb91f1e9b002d908 should have fixed that. v.0.0.19 is published to npm.
